// Set a name for the current cache
let cacheName = 'ChampionA-Z'; 

// Default files to always cache

let cacheFiles = [
	"./",
	"/manifest.json",
    "/css/style.css",
    "/data/completeChamp.html",
    "/data/names.html",
    "/fonts/BeaufortforLOL-Regular.ttf",
    "/images/icons/icon-512x512.png",
    "/images/cursor.png",
    "/js/app.js",
    "/modules/lib.js",
    "/modules/db.js",
    "/modules/install.js",
    "/modules/idb-src.js",
    "/modules/main.js",
    "/modules/championList.js",
    "/modules/completeChampion.js",
    "/modules/handleNav.js",
    "/modules/pagination.js",
    "/modules/playersForm.js",
    "/favicon.ico",
    "/index.html",
   "/audio/Aatrox-Ban.mp3",
   "/audio/Aatrox-Pick.mp3",
   "/audio/Ahri-Ban.mp3",
   "/audio/Ahri-Pick.mp3",
   "/audio/Akali-Ban.mp3",
   "/audio/Akali-Pick.mp3",
   "/audio/Akshan-Ban.mp3",
   "/audio/Akshan-Pick.mp3",
   "/audio/Alistar-Ban.mp3",
   "/audio/Alistar-Pick.mp3",
   "/audio/Amumu-Ban.mp3",
   "/audio/Amumu-Pick.mp3",
   "/audio/Anivia-Ban.mp3",
   "/audio/Anivia-Pick.mp3",
   "/audio/Annie-Ban.mp3",
   "/audio/Annie-Pick.mp3",
   "/audio/Aphelios-Ban.mp3",
   "/audio/Aphelios-Pick.mp3",
   "/audio/Ashe-Ban.mp3",
   "/audio/Ashe-Pick.mp3",
   "/audio/AurelionSol-Ban.mp3",
   "/audio/AurelionSol-Pick.mp3",
   "/audio/Azir-Ban.mp3",
   "/audio/Azir-Pick.mp3",
   "/audio/Bard-Ban.mp3",
   "/audio/Bard-Pick.mp3",
   "/audio/Bel'Veth-Ban.mp3",
   "/audio/Bel'Veth-Pick.mp3",
   "/audio/Blitzcrank-Ban.mp3",
   "/audio/Blitzcrank-Pick.mp3",
   "/audio/Brand-Ban.mp3",
   "/audio/Brand-Pick.mp3",
   "/audio/Braum-Ban.mp3",
   "/audio/Braum-Pick.mp3",
   "/audio/Caitlyn-Ban.mp3",
   "/audio/Caitlyn-Pick.mp3",
   "/audio/Camille-Ban.mp3",
   "/audio/Camille-Pick.mp3",
   "/audio/Cassiopeia-Ban.mp3",
   "/audio/Cassiopeia-Pick.mp3",
   "/audio/Cho'Gath-Ban.mp3",
   "/audio/Cho'Gath-Pick.mp3",
   "/audio/Corki-Ban.mp3",
   "/audio/Corki-Pick.mp3",
   "/audio/Darius-Ban.mp3",
   "/audio/Darius-Pick.mp3",
   "/audio/Diana-Ban.mp3",
   "/audio/Diana-Pick.mp3",
   "/audio/Dr.Mundo-Ban.mp3",
   "/audio/Dr.Mundo-Pick.mp3",
   "/audio/Draven-Ban.mp3",
   "/audio/Draven-Pick.mp3",
   "/audio/Ekko-Ban.mp3",
   "/audio/Ekko-Pick.mp3",
   "/audio/Elise-Ban.mp3",
   "/audio/Elise-Pick.mp3",
   "/audio/Evelynn-Ban.mp3",
   "/audio/Evelynn-Pick.mp3",
   "/audio/Ezreal-Ban.mp3",
   "/audio/Ezreal-Pick.mp3",
   "/audio/Fiddlesticks-Ban.mp3",
   "/audio/Fiddlesticks-Pick.mp3",
   "/audio/Fiora-Ban.mp3",
   "/audio/Fiora-Pick.mp3",
   "/audio/Fizz-Ban.mp3",
   "/audio/Fizz-Pick.mp3",
   "/audio/Galio-Ban.mp3",
   "/audio/Galio-Pick.mp3",
   "/audio/Gangplank-Ban.mp3",
   "/audio/Gangplank-Pick.mp3",
   "/audio/Garen-Ban.mp3",
   "/audio/Garen-Pick.mp3",
   "/audio/Gnar-Ban.mp3",
   "/audio/Gnar-Pick.mp3",
   "/audio/Gragas-Ban.mp3",
   "/audio/Gragas-Pick.mp3",
   "/audio/Graves-Ban.mp3",
   "/audio/Graves-Pick.mp3",
   "/audio/Gwen-Ban.mp3",
   "/audio/Gwen-Pick.mp3",
   "/audio/Hecarim-Ban.mp3",
   "/audio/Hecarim-Pick.mp3",
   "/audio/Heimerdinger-Ban.mp3",
   "/audio/Heimerdinger-Pick.mp3",
   "/audio/Illaoi-Ban.mp3",
   "/audio/Illaoi-Pick.mp3",
   "/audio/Irelia-Ban.mp3",
   "/audio/Irelia-Pick.mp3",
   "/audio/Ivern-Ban.mp3",
   "/audio/Ivern-Pick.mp3",
   "/audio/Janna-Ban.mp3",
   "/audio/Janna-Pick.mp3",
   "/audio/JarvanIV-Ban.mp3",
   "/audio/JarvanIV-Pick.mp3",
   "/audio/Jax-Ban.mp3",
   "/audio/Jax-Pick.mp3",
   "/audio/Jayce-Ban.mp3",
   "/audio/Jayce-Pick.mp3",
   "/audio/Jhin-Ban.mp3",
   "/audio/Jhin-Pick.mp3",
   "/audio/Jinx-Ban.mp3",
   "/audio/Jinx-Pick.mp3",
   "/audio/K'Sante-Ban.mp3",
   "/audio/K'Sante-Pick.mp3",
   "/audio/Kai'Sa-Ban.mp3",
   "/audio/Kai'Sa-Pick.mp3",
   "/audio/Kalista-Ban.mp3",
   "/audio/Kalista-Pick.mp3",
   "/audio/Karma-Ban.mp3",
   "/audio/Karma-Pick.mp3",
   "/audio/Karthus-Ban.mp3",
   "/audio/Karthus-Pick.mp3",
   "/audio/Kassadin-Ban.mp3",
   "/audio/Kassadin-Pick.mp3",
   "/audio/Katarina-Ban.mp3",
   "/audio/Katarina-Pick.mp3",
   "/audio/Kayle-Ban.mp3",
   "/audio/Kayle-Pick.mp3",
   "/audio/Kayn-Ban.mp3",
   "/audio/Kayn-Pick.mp3",
   "/audio/Kennen-Ban.mp3",
   "/audio/Kennen-Pick.mp3",
   "/audio/Kha'Zix-Ban.mp3",
   "/audio/Kha'Zix-Pick.mp3",
   "/audio/Kindred-Ban.mp3",
   "/audio/Kindred-Pick.mp3",
   "/audio/Kled-Ban.mp3",
   "/audio/Kled-Pick.mp3",
   "/audio/Kog'Maw-Ban.mp3",
   "/audio/Kog'Maw-Pick.mp3",
   "/audio/LeBlanc-Ban.mp3",
   "/audio/LeBlanc-Pick.mp3",
   "/audio/LeeSin-Ban.mp3",
   "/audio/LeeSin-Pick.mp3",
   "/audio/Leona-Ban.mp3",
   "/audio/Leona-Pick.mp3",
   "/audio/Lillia-Ban.mp3",
   "/audio/Lillia-Pick.mp3",
   "/audio/Lissandra-Ban.mp3",
   "/audio/Lissandra-Pick.mp3",
   "/audio/Lucian-Ban.mp3",
   "/audio/Lucian-Pick.mp3",
   "/audio/Lulu-Ban.mp3",
   "/audio/Lulu-Pick.mp3",
   "/audio/Lux-Ban.mp3",
   "/audio/Lux-Pick.mp3",
   "/audio/Malphite-Ban.mp3",
   "/audio/Malphite-Pick.mp3",
   "/audio/Malzahar-Ban.mp3",
   "/audio/Malzahar-Pick.mp3",
   "/audio/Maokai-Ban.mp3",
   "/audio/Maokai-Pick.mp3",
   "/audio/MasterYi-Ban.mp3",
   "/audio/MasterYi-Pick.mp3",
   "/audio/Milio-Ban.mp3",
   "/audio/Milio-Pick.mp3",
   "/audio/MissFortune-Ban.mp3",
   "/audio/MissFortune-Pick.mp3",
   "/audio/Mordekaiser-Ban.mp3",
   "/audio/Mordekaiser-Pick.mp3",
   "/audio/Morgana-Ban.mp3",
   "/audio/Morgana-Pick.mp3",
   "/audio/Nami-Ban.mp3",
   "/audio/Nami-Pick.mp3",
   "/audio/Nasus-Ban.mp3",
   "/audio/Nasus-Pick.mp3",
   "/audio/Nautilus-Ban.mp3",
   "/audio/Nautilus-Pick.mp3",
   "/audio/Neeko-Ban.mp3",
   "/audio/Neeko-Pick.mp3",
   "/audio/Nidalee-Ban.mp3",
   "/audio/Nidalee-Pick.mp3",
   "/audio/Nilah-Ban.mp3",
   "/audio/Nilah-Pick.mp3",
   "/audio/Nocturne-Ban.mp3",
   "/audio/Nocturne-Pick.mp3",
   "/audio/Nunu&Willump-Ban.mp3",
   "/audio/Nunu&Willump-Pick.mp3",
   "/audio/Olaf-Ban.mp3",
   "/audio/Olaf-Pick.mp3",
   "/audio/Orianna-Ban.mp3",
   "/audio/Orianna-Pick.mp3",
   "/audio/Ornn-Ban.mp3",
   "/audio/Ornn-Pick.mp3",
   "/audio/Pantheon-Ban.mp3",
   "/audio/Pantheon-Pick.mp3",
   "/audio/Poppy-Ban.mp3",
   "/audio/Poppy-Pick.mp3",
   "/audio/Pyke-Ban.mp3",
   "/audio/Pyke-Pick.mp3",
   "/audio/Qiyana-Ban.mp3",
   "/audio/Qiyana-Pick.mp3",
   "/audio/Quinn-Ban.mp3",
   "/audio/Quinn-Pick.mp3",
   "/audio/Rakan-Ban.mp3",
   "/audio/Rakan-Pick.mp3",
   "/audio/Rammus-Ban.mp3",
   "/audio/Rammus-Pick.mp3",
   "/audio/Rek'Sai-Ban.mp3",
   "/audio/Rek'Sai-Pick.mp3",
   "/audio/Rell-Ban.mp3",
   "/audio/Rell-Pick.mp3",
   "/audio/RenataGlasc-Ban.mp3",
   "/audio/RenataGlasc-Pick.mp3",
   "/audio/Renekton-Ban.mp3",
   "/audio/Renekton-Pick.mp3",
   "/audio/Rengar-Ban.mp3",
   "/audio/Rengar-Pick.mp3",
   "/audio/Riven-Ban.mp3",
   "/audio/Riven-Pick.mp3",
   "/audio/Rumble-Ban.mp3",
   "/audio/Rumble-Pick.mp3",
   "/audio/Ryze-Ban.mp3",
   "/audio/Ryze-Pick.mp3",
   "/audio/Samira-Ban.mp3",
   "/audio/Samira-Pick.mp3",
   "/audio/Sejuani-Ban.mp3",
   "/audio/Sejuani-Pick.mp3",
   "/audio/Senna-Ban.mp3",
   "/audio/Senna-Pick.mp3",
   "/audio/Seraphine-Ban.mp3",
   "/audio/Seraphine-Pick.mp3",
   "/audio/Sett-Ban.mp3",
   "/audio/Sett-Pick.mp3",
   "/audio/Shaco-Ban.mp3",
   "/audio/Shaco-Pick.mp3",
   "/audio/Shen-Ban.mp3",
   "/audio/Shen-Pick.mp3",
   "/audio/Shyvana-Ban.mp3",
   "/audio/Shyvana-Pick.mp3",
   "/audio/Singed-Ban.mp3",
   "/audio/Singed-Pick.mp3",
   "/audio/Sion-Ban.mp3",
   "/audio/Sion-Pick.mp3",
   "/audio/Sivir-Ban.mp3",
   "/audio/Sivir-Pick.mp3",
   "/audio/Skarner-Ban.mp3",
   "/audio/Skarner-Pick.mp3",
   "/audio/Sona-Ban.mp3",
   "/audio/Sona-Pick.mp3",
   "/audio/Soraka-Ban.mp3",
   "/audio/Soraka-Pick.mp3",
   "/audio/Swain-Ban.mp3",
   "/audio/Swain-Pick.mp3",
   "/audio/Sylas-Ban.mp3",
   "/audio/Sylas-Pick.mp3",
   "/audio/Syndra-Ban.mp3",
   "/audio/Syndra-Pick.mp3",
   "/audio/TahmKench-Ban.mp3",
   "/audio/TahmKench-Pick.mp3",
   "/audio/Taliyah-Ban.mp3",
   "/audio/Taliyah-Pick.mp3",
   "/audio/Talon-Ban.mp3",
   "/audio/Talon-Pick.mp3",
   "/audio/Taric-Ban.mp3",
   "/audio/Taric-Pick.mp3",
   "/audio/Teemo-Ban.mp3",
   "/audio/Teemo-Pick.mp3",
   "/audio/Thresh-Ban.mp3",
   "/audio/Thresh-Pick.mp3",
   "/audio/Tristana-Ban.mp3",
   "/audio/Tristana-Pick.mp3",
   "/audio/Trundle-Ban.mp3",
   "/audio/Trundle-Pick.mp3",
   "/audio/Tryndamere-Ban.mp3",
   "/audio/Tryndamere-Pick.mp3",
   "/audio/TwistedFate-Ban.mp3",
   "/audio/TwistedFate-Pick.mp3",
   "/audio/Twitch-Ban.mp3",
   "/audio/Twitch-Pick.mp3",
   "/audio/Udyr-Ban.mp3",
   "/audio/Udyr-Pick.mp3",
   "/audio/Urgot-Ban.mp3",
   "/audio/Urgot-Pick.mp3",
   "/audio/Varus-Ban.mp3",
   "/audio/Varus-Pick.mp3",
   "/audio/Vayne-Ban.mp3",
   "/audio/Vayne-Pick.mp3",
   "/audio/Veigar-Ban.mp3",
   "/audio/Veigar-Pick.mp3",
   "/audio/Vel'Koz-Ban.mp3",
   "/audio/Vel'Koz-Pick.mp3",
   "/audio/Vex-Ban.mp3",
   "/audio/Vex-Pick.mp3",
   "/audio/Vi-Ban.mp3",
   "/audio/Vi-Pick.mp3",
   "/audio/Viego-Ban.mp3",
   "/audio/Viego-Pick.mp3",
   "/audio/Viktor-Ban.mp3",
   "/audio/Viktor-Pick.mp3",
   "/audio/Vladimir-Ban.mp3",
   "/audio/Vladimir-Pick.mp3",
   "/audio/Volibear-Ban.mp3",
   "/audio/Volibear-Pick.mp3",
   "/audio/Warwick-Ban.mp3",
   "/audio/Warwick-Pick.mp3",
   "/audio/Wukong-Ban.mp3",
   "/audio/Wukong-Pick.mp3",
   "/audio/Xayah-Ban.mp3",
   "/audio/Xayah-Pick.mp3",
   "/audio/Xerath-Ban.mp3",
   "/audio/Xerath-Pick.mp3",
   "/audio/XinZhao-Ban.mp3",
   "/audio/XinZhao-Pick.mp3",
   "/audio/Yasuo-Ban.mp3",
   "/audio/Yasuo-Pick.mp3",
   "/audio/Yone-Ban.mp3",
   "/audio/Yone-Pick.mp3",
   "/audio/Yorick-Ban.mp3",
   "/audio/Yorick-Pick.mp3",
   "/audio/Yuumi-Ban.mp3",
   "/audio/Yuumi-Pick.mp3",
   "/audio/Zac-Ban.mp3",
   "/audio/Zac-Pick.mp3",
   "/audio/Zed-Ban.mp3",
   "/audio/Zed-Pick.mp3",
   "/audio/Zeri-Ban.mp3",
   "/audio/Zeri-Pick.mp3",
   "/audio/Ziggs-Ban.mp3",
   "/audio/Ziggs-Pick.mp3",
   "/audio/Zilean-Ban.mp3",
   "/audio/Zilean-Pick.mp3",
   "/audio/Zoe-Ban.mp3",
   "/audio/Zoe-Pick.mp3",
   "/audio/Zyra-Ban.mp3",
   "/audio/Zyra-Pick.mp3"
];

self.addEventListener('install', function(event) {
    event.waitUntil(
      caches.open(cacheName).then(function(cache) {
        return Promise.all(
          cacheFiles.map(function(url) {
            return fetch(url).then(function(response) {
              if (!response.ok) {
                throw new Error('Fehler beim Abrufen der Datei: ' + url);
              }
              return cache.put(url, response);
            });
          })
        );
      }).then(function() {
        console.log('Dateien wurden erfolgreich im Cache zwischengespeichert:');
      }).catch(function(error) {
        console.error('Fehler beim Zwischenspeichern der Dateien im Cache:', error);
      })
    );
  });


self.addEventListener('activate', function(e) {
    console.log('[ServiceWorker] Activated');

    e.waitUntil(

    	// Get all the cache keys (cacheName)
		caches.keys().then(function(cacheNames) {
			return Promise.all(cacheNames.map(function(thisCacheName) {

				// If a cached item is saved under a previous cacheName
				if (thisCacheName !== cacheName) {

					// Delete that cached file
					console.log('[ServiceWorker] Removing Cached Files from Cache - ', thisCacheName);
					return caches.delete(thisCacheName);
				}
			}));
		})
	); // end e.waitUntil

});


self.addEventListener('fetch', function(event) {
    if (event.request.url.includes('https://ddragon.leagueoflegends.com/cdn/')) {
      return; // Die Anfrage auf Bilder aus der API wird nicht weiter verarbeitet
    }
  
    event.respondWith(
      caches.match(event.request).then(function(response) {
        return response || fetch(event.request).then(function(response) {
          if (!response) {
            console.log("[ServiceWorker] Keine Antwort von fetch");
            return response;
          }
  
          var responseClone = response.clone();
          caches.open(cacheName).then(function(cache) {
            cache.put(event.request, responseClone);
            console.log('[ServiceWorker] Neue Daten zwischengespeichert', event.request.url);
          });
  
          return response;
        }).catch(function(err) {
          console.log('[ServiceWorker] Fehler beim Abrufen und Zwischenspeichern neuer Daten', err);
        });
      })
    );
  });
  
